# Generated by Django 2.2 on 2021-03-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_A_Z', '0002_side_effects_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='side_effects_data',
        ),
    ]
