# Generated by Django 3.1.7 on 2021-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Med_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medication_Name', models.CharField(max_length=500)),
                ('Dosage', models.CharField(max_length=500)),
                ('Instructions', models.CharField(max_length=500)),
            ],
        ),
    ]
