# Generated by Django 3.1.7 on 2021-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='side_effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
